channels:
  - conda-forge
dependencies:
  - python=3.9.16
  - pip=22.1.2
  - pip:
    - robotframework-browser==17.2.0
    - rpaframework==24.1.2
    - pandas==2.2.0
    - nltk==3.8.1
rccPostInstall:
  - rfbrowser init